### ISSUE TITLE
Robot.chooser not initialized in constructor and dereferenced in org.usfirst.frc.team2729.robot.Robot.autonomousInit()

### ISSUE THREAD

**Issue by rjbohinski** [2729StormRobotics/Storm2016#3]
This field is never initialized within any constructor, and is therefore could be null after the object is constructed. Elsewhere, it is loaded and dereferenced without a null check. This could be a either an error or a questionable design, since it means a null pointer exception will be generated if that field is dereferenced before being initialized.

```
public void autonomousInit() {
    autonomousCommand = (Command) chooser.getSelected();
```

**Comment by geekman7473** [comment]
Is initialized in robotInit which is ALWAYS run before autoInit. Robot necessarily has no constructor, as per WPI Lib stricture.
